[theme]
primaryColor = "#4991f5"
backgroundColor = "#f5f5f5"
secondaryBackgroundColor = "#7ca0fb"
textColor = "#0a0a0a"
font = "sans serif"

[server]
port = 8501

[runner]
magicEnabled = false

[browser]
gatherUsageStats = false
